### ISSUE TITLE
Kernel 4.13

### ISSUE THREAD

**Issue by AndyLavr** [pbnelson/rotswap#8]
Hi,

From kernel 4.13:

Evdev Axis Inversion doesnt exist...
Evdev Axis Swap doesnt exist...

:(

https://github.com/AndyLavr/Aspire-SW5-012_Kernel_4.13

https://drive.google.com/drive/folders/0B5ngHZIeNdyTUjEtUjVDbU5FYlk

**Comment by pbnelson** [comment]
Looks like something changed in the kernel so the name of that property changed. Lot's of "me too" reports on this page: https://www.raspberrypi.org/forums/viewtopic.php?t=172025

I'll have to do the upgrade so I can recreate the problem and work out a solution.

**Comment by pbnelson** [comment]
Well, I've done the upgrade, and poked around for two hours. There's no way to get this script working on Ubuntu 17.1 because they broke `xrandr`. On the other hand, built-in auto-rotation is working, just backwards. My workaround is to get the rotate the tablet until screen orientation is as desired, then use the taskbar to lock the current orientation. See https://askubuntu.com/questions/968169/screen-randomly-rotates-on-ubuntu-17-10 for more info.
